//! GENERATED by tools/gen_crs_registry.py — do not edit by hand.
//!
//! The GCR1 registry blob + stamped sizes/versions. See ../plans/registry-format.org.

pub(super) const REGISTRY_BLOB_ZSTD: &[u8] = include_bytes!("registry.bin.zst");
pub(super) const REGISTRY_BLOB_RAW_SIZE: usize = 43084507;
pub(super) const CRS_COUNT: usize = 13790;
pub(super) static DATASET_VERSIONS: &[(&str, &str)] = &[
    ("EPSG", "v12.029"),
    ("PROJ", "9.8.1"),
    ("ESRI", "ArcGIS Pro 3.6"),
    ("IGNF", "3.1.0"),
    ("NKG", "1.0.w"),
    ("proj.db.layout", "1.6"),
    ("generated", "2026-08-12"),
];
